import type { PartidoData } from '../types'

/** Concurso 2333 — Progol (Lotería Nacional). Jornada Mayo 2026. */
export const PARTIDOS: PartidoData[] = [
  {
    id: 1,
    local: 'América',
    visitante: 'Chivas',
    dia: 'Sáb 16',
    hora: '20:10',
    escudoLocal: '🟡',
    escudoVisitante: '🔴',
    h2h: { local: 3, empate: 1, visitante: 2 },
    formaLocal: ['V', 'V', 'E', 'V', 'V'],
    formaVisitante: ['D', 'V', 'E', 'V', 'D'],
    momio: { uno: 1.85, equis: 3.45, dos: 4.1 },
    dificultad: 'amarillo',
    codigoLN: '101',
  },
  {
    id: 2,
    local: 'Monterrey',
    visitante: 'Tigres',
    dia: 'Sáb 16',
    hora: '22:15',
    escudoLocal: '🔵',
    escudoVisitante: '🟡',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['V', 'V', 'V', 'D', 'V'],
    formaVisitante: ['V', 'E', 'V', 'V', 'V'],
    momio: { uno: 2.3, equis: 3.2, dos: 2.95 },
    dificultad: 'rojo',
    codigoLN: '102',
  },
  {
    id: 3,
    local: 'Cruz Azul',
    visitante: 'Pumas',
    dia: 'Dom 17',
    hora: '12:00',
    escudoLocal: '🔵',
    escudoVisitante: '🟡',
    h2h: { local: 2, empate: 3, visitante: 0 },
    formaLocal: ['V', 'E', 'V', 'V', 'E'],
    formaVisitante: ['E', 'D', 'E', 'V', 'E'],
    momio: { uno: 1.95, equis: 3.5, dos: 3.6 },
    dificultad: 'verde',
    codigoLN: '103',
  },
  {
    id: 4,
    local: 'Toluca',
    visitante: 'Pachuca',
    dia: 'Dom 17',
    hora: '17:00',
    escudoLocal: '🔴',
    escudoVisitante: '⚪',
    h2h: { local: 1, empate: 2, visitante: 2 },
    formaLocal: ['V', 'D', 'V', 'E', 'D'],
    formaVisitante: ['E', 'V', 'V', 'D', 'V'],
    momio: { uno: 2.55, equis: 3.3, dos: 2.7 },
    dificultad: 'rojo',
    codigoLN: '104',
  },
  {
    id: 5,
    local: 'León',
    visitante: 'Santos',
    dia: 'Dom 17',
    hora: '19:05',
    escudoLocal: '🟢',
    escudoVisitante: '🟢',
    h2h: { local: 2, empate: 1, visitante: 2 },
    formaLocal: ['D', 'E', 'V', 'V', 'V'],
    formaVisitante: ['D', 'D', 'E', 'D', 'E'],
    momio: { uno: 2.1, equis: 3.4, dos: 3.15 },
    dificultad: 'verde',
    codigoLN: '105',
  },
  {
    id: 6,
    local: 'Atlas',
    visitante: 'Juárez',
    dia: 'Dom 17',
    hora: '21:10',
    escudoLocal: '⚫',
    escudoVisitante: '🟢',
    h2h: { local: 1, empate: 3, visitante: 1 },
    formaLocal: ['D', 'E', 'D', 'V', 'E'],
    formaVisitante: ['E', 'E', 'D', 'D', 'V'],
    momio: { uno: 2.35, equis: 3.25, dos: 2.9 },
    dificultad: 'amarillo',
    codigoLN: '106',
  },
  {
    id: 7,
    local: 'Querétaro',
    visitante: 'Mazatlán',
    dia: 'Lun 18',
    hora: '20:00',
    escudoLocal: '🔵',
    escudoVisitante: '🟣',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['E', 'V', 'D', 'E', 'D'],
    formaVisitante: ['D', 'D', 'V', 'E', 'E'],
    momio: { uno: 2.4, equis: 3.3, dos: 2.85 },
    dificultad: 'amarillo',
    codigoLN: '107',
  },
  {
    id: 8,
    local: 'Necaxa',
    visitante: 'Puebla',
    dia: 'Dom 17',
    hora: '17:00',
    escudoLocal: '🔴',
    escudoVisitante: '🔵',
    h2h: { local: 1, empate: 2, visitante: 2 },
    formaLocal: ['V', 'E', 'D', 'V', 'E'],
    formaVisitante: ['E', 'D', 'D', 'E', 'V'],
    momio: { uno: 2.2, equis: 3.35, dos: 3.05 },
    dificultad: 'amarillo',
    codigoLN: '108',
  },
  {
    id: 9,
    local: 'Tijuana',
    visitante: 'San Luis',
    dia: 'Dom 17',
    hora: '19:00',
    escudoLocal: '🔴',
    escudoVisitante: '🟡',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['D', 'V', 'V', 'E', 'D'],
    formaVisitante: ['E', 'D', 'V', 'V', 'E'],
    momio: { uno: 2.15, equis: 3.4, dos: 3.1 },
    dificultad: 'rojo',
    codigoLN: '109',
  },
  {
    id: 10,
    local: 'Barcelona',
    visitante: 'Real Madrid',
    dia: 'Dom 17',
    hora: '14:00',
    escudoLocal: '🔵',
    escudoVisitante: '⚪',
    h2h: { local: 2, empate: 1, visitante: 3 },
    formaLocal: ['V', 'V', 'V', 'E', 'V'],
    formaVisitante: ['V', 'V', 'V', 'V', 'D'],
    momio: { uno: 2.55, equis: 3.45, dos: 2.6 },
    dificultad: 'rojo',
    codigoLN: '110',
  },
  {
    id: 11,
    local: 'Liverpool',
    visitante: 'Manchester City',
    dia: 'Sáb 16',
    hora: '11:30',
    escudoLocal: '🔴',
    escudoVisitante: '🔵',
    h2h: { local: 1, empate: 2, visitante: 2 },
    formaLocal: ['V', 'V', 'E', 'V', 'V'],
    formaVisitante: ['V', 'E', 'V', 'V', 'V'],
    momio: { uno: 2.7, equis: 3.5, dos: 2.45 },
    dificultad: 'rojo',
    codigoLN: '111',
  },
  {
    id: 12,
    local: 'Bayern Múnich',
    visitante: 'Borussia Dortmund',
    dia: 'Sáb 16',
    hora: '12:30',
    escudoLocal: '🔴',
    escudoVisitante: '🟡',
    h2h: { local: 3, empate: 1, visitante: 1 },
    formaLocal: ['V', 'V', 'V', 'V', 'E'],
    formaVisitante: ['V', 'E', 'V', 'D', 'V'],
    momio: { uno: 1.75, equis: 4.0, dos: 4.2 },
    dificultad: 'verde',
    codigoLN: '112',
  },
  {
    id: 13,
    local: 'LAFC',
    visitante: 'Inter Miami',
    dia: 'Dom 17',
    hora: '19:30',
    escudoLocal: '⚫',
    escudoVisitante: '🩷',
    h2h: { local: 1, empate: 1, visitante: 0 },
    formaLocal: ['V', 'V', 'D', 'E', 'V'],
    formaVisitante: ['V', 'V', 'V', 'V', 'E'],
    momio: { uno: 2.05, equis: 3.6, dos: 3.2 },
    dificultad: 'amarillo',
    codigoLN: '113',
  },
  {
    id: 14,
    local: 'América (F)',
    visitante: 'Tigres (F)',
    dia: 'Lun 18',
    hora: '21:00',
    escudoLocal: '🟡',
    escudoVisitante: '🟡',
    h2h: { local: 0, empate: 0, visitante: 0 },
    formaLocal: ['V', 'V', 'V', 'V', 'V'],
    formaVisitante: ['V', 'D', 'V', 'V', 'V'],
    momio: { uno: 2.0, equis: 3.5, dos: 3.3 },
    dificultad: 'rojo',
    codigoLN: null, // S/P — Sin Pronóstico (Liga MX Femenil sin cruces previos)
  },
]
